### ISSUE TITLE
Other k dialects?

### ISSUE THREAD

**Issue by ghost** [gitonthescene/ngnk-libs#2]
Was it your intention to focus these explorations to ngn/k dialect in particular?

I will be translating some of your code to other dialects with open source interpreter implementation as practice. I thought it could be interesting if this repository becomes central place to discuss problem solving technique with k in general. We could specify dialect being used in comment or file name.

Otherwise I could host it separately.

**Comment by gitonthescene** [comment]
That's actually a good question.  The original intention was specifically about ngn/k.  I do think it's nice to have each language separated out so as not to muddle the information for people seeking specific code for a specific language.

I'm not sure what the right "big picture" solution should be but in the short term the [K wiki](https://wiki.cor.fyi/wiki/Main_Page) could be used as a hub.

**Comment by ghost** [comment]
Understood. I will not attempt to pull in k code written for other dialects.

I think K wiki's learning material page can be revamped to entice newcomers to try out specific tracks based on their taste (trying bite sized projects are indeed the best way to learn a new language for sure).

**Comment by gitonthescene** [comment]
It is a wiki after all.  I'd bet razetime would love to have contributions.  Maybe I could add some general purpose info about using ffi say.
